"""Generate a measured ATT&CK coverage report from the rules and captured logs.

A rule counts as verified only if it fires on every one of its captured
attack scenarios and on no line of any captured benign scenario. Output goes
to docs/coverage.md and docs/navigator_layer.json.

Run from the repo root:  python3 -m tools.coverage_report
"""
import json
import re
from pathlib import Path

import yaml

from tools.sigma_lite import load_rules, matches

ROOT = Path(__file__).resolve().parent.parent
FIXTURES = yaml.safe_load((ROOT / "tests" / "fixtures.yml").read_text())
WAZUH_MAP = yaml.safe_load((ROOT / "tools" / "wazuh_map.yml").read_text())
CAPTURED = ROOT / "tests" / "captured"
OUT_DIR = ROOT / "docs"
TECHNIQUE = re.compile(r"^attack\.(t\d{4}(?:\.\d{3})?)$")


def read(name):
    return (CAPTURED / f"{name}.log").read_text().splitlines()


def is_verified(rule):
    attacks = FIXTURES["rules"][rule["id"]]["attack"]
    fires = all(any(matches(rule, line) for line in read(n)) for n in attacks)
    quiet = not any(
        matches(rule, line) for n in FIXTURES["benign"] for line in read(n)
    )
    return fires and quiet


def describe(rule):
    techniques = [m.group(1).upper() for t in rule["tags"]
                  if (m := TECHNIQUE.match(t))]
    tactics = [t.split(".", 1)[1].replace("_", " ").title()
               for t in rule["tags"]
               if t.startswith("attack.") and not TECHNIQUE.match(t)]
    return techniques, tactics


def rows():
    out = []
    for rule in load_rules():
        techniques, tactics = describe(rule)
        out.append({
            "rule": rule["_file"],
            "title": rule["title"],
            "techniques": techniques,
            "tactics": tactics,
            "wazuh_id": WAZUH_MAP[rule["id"]]["wazuh_id"],
            "verified": is_verified(rule),
        })
    return out


def render_markdown():
    data = rows()
    covered = sorted({t for r in data if r["verified"] for t in r["techniques"]})
    lines = [
        "# ATT&CK coverage",
        "",
        "Generated by `tools/coverage_report.py`. Do not edit by hand.",
        "",
        "A rule is verified only if it fires on every captured attack "
        "scenario and on no line of any captured benign scenario.",
        "",
        "| Technique | Tactic | Rule | Wazuh id | Verified |",
        "|-----------|--------|------|----------|----------|",
    ]
    for r in data:
        lines.append(
            f"| {', '.join(r['techniques'])} | {', '.join(r['tactics'])} "
            f"| `{r['rule']}` | {r['wazuh_id']} "
            f"| {'yes' if r['verified'] else 'NO'} |"
        )
    lines += [
        "",
        f"Verified techniques: {len(covered)} ({', '.join(covered)})",
        "",
        "Coverage means tested against captures from one lab VM, for the "
        "exact commands in `tools/run_scenarios.sh`. It says nothing about "
        "other ways to perform the same technique.",
    ]
    return "\n".join(lines) + "\n"

def render_layer():
    by_technique = {}
    for r in rows():
        if not r["verified"]:
            continue
        for t in r["techniques"]:
            by_technique.setdefault(t, []).append(
                f"{r['title']} (Wazuh rule {r['wazuh_id']})"
            )
    techniques = [
        {
            "techniqueID": t,
            "score": 1,
            "comment": "; ".join(names) + ", verified by log replay",
        }
        for t, names in sorted(by_technique.items())
    ]
    layer = {
        "name": "Detection Lab coverage",
        "versions": {"attack": "17", "navigator": "5.1.0", "layer": "4.5"},
        "domain": "enterprise-attack",
        "description": "Techniques with a detection that passes replay tests "
                       "against captured logs.",
        "sorting": 3,
        "gradient": {"colors": ["#ffffff", "#2e7d32"],
                     "minValue": 0, "maxValue": 1},
        "techniques": techniques,
    }
    return json.dumps(layer, indent=2) + "\n"



def main():
    OUT_DIR.mkdir(exist_ok=True)
    (OUT_DIR / "coverage.md").write_text(render_markdown())
    (OUT_DIR / "navigator_layer.json").write_text(render_layer())
    print("wrote docs/coverage.md and docs/navigator_layer.json")


if __name__ == "__main__":
    main()
