"""Convert the Sigma rules in rules/ into a Wazuh rules file.

Handles the same subset as sigma_lite: keyword blocks joined by
`and` / `and not`. Each Sigma rule needs an entry in tools/wazuh_map.yml.
The whole condition becomes one PCRE2 regex built with lookaheads, so each
Wazuh rule needs only a single <regex> tag. A rule with an if_sid hangs off
that built-in rule; a rule without one matches on the program name.

Run from the repo root:  python3 -m tools.sigma_to_wazuh
"""
import re
from pathlib import Path
from xml.sax.saxutils import escape

import yaml

from tools.sigma_lite import load_rules, validate

ROOT = Path(__file__).resolve().parent.parent
MAP = ROOT / "tools" / "wazuh_map.yml"
OUT = ROOT / "wazuh" / "detection_lab_rules.xml"
LEVELS = {"informational": 3, "low": 5, "medium": 8, "high": 10, "critical": 12}
TECHNIQUE = re.compile(r"^attack\.(t\d{4}(?:\.\d{3})?)$")


def parse_condition(condition):
    blocks, negate = [], False
    for tok in condition.split():
        if tok == "and":
            continue
        if tok == "or":
            raise ValueError("'or' conditions are not supported")
        if tok == "not":
            negate = True
            continue
        blocks.append((tok, negate))
        negate = False
    return blocks


def to_pcre(item, program):
    prefix = program.lower() + "*"
    if item.lower().startswith(prefix):
        item = item[len(prefix):]
    return ".*".join(re.escape(part) for part in item.split("*"))


def build_pattern(rule, program):
    det = rule["detection"]
    out = "(?i)^"
    for block, negated in parse_condition(det["condition"]):
        alts = "|".join(to_pcre(i, program) for i in det[block])
        out += f"(?{'!' if negated else '='}.*(?:{alts}))"
    return out


def build_rule(rule, meta):
    techniques = [m.group(1).upper() for t in rule["tags"]
                  if (m := TECHNIQUE.match(t))]
    pattern = escape(build_pattern(rule, meta["program"]))
    lines = [
        f"  <!-- sigma: {rule['id']} ({rule['_file']}) -->",
        f'  <rule id="{meta["wazuh_id"]}" level="{LEVELS[rule["level"]]}">',
    ]
    if meta.get("if_sid"):
        lines.append(f'    <if_sid>{meta["if_sid"]}</if_sid>')
    else:
        lines.append(
            f'    <program_name>{escape(meta["program"])}</program_name>'
        )
    lines += [
        f'    <regex type="pcre2">{pattern}</regex>',
        f'    <description>{escape(rule["title"])}</description>',
    ]
    for tech in techniques:
        lines.append(f"    <mitre><id>{tech}</id></mitre>")
    lines.append("  </rule>")
    return "\n".join(lines)


def render():
    meta_map = yaml.safe_load(MAP.read_text())
    parts = [
        "<!-- Generated by tools/sigma_to_wazuh.py from rules/*.yml. "
        "Do not edit by hand. -->",
        '<group name="detection_lab,">',
    ]
    seen = set()
    for rule in load_rules():
        errors = validate(rule)
        if errors:
            raise SystemExit(f"{rule['_file']}: {errors}")
        meta = meta_map.get(rule["id"])
        if meta is None:
            raise SystemExit(f"{rule['_file']}: no entry in wazuh_map.yml")
        if meta["wazuh_id"] in seen:
            raise SystemExit(f"duplicate wazuh_id {meta['wazuh_id']}")
        seen.add(meta["wazuh_id"])
        parts.append(build_rule(rule, meta))
    parts.append("</group>")
    return "\n".join(parts) + "\n"


def main():
    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text(render())
    print(f"wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()


if __name__ == "__main__":
    main()
